//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionConsommationVehiculeMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class affectation
    {
        public int Id { get; set; }
        public int IdVehicule { get; set; }
        public int IdService { get; set; }
        public int IdUser { get; set; }
        public System.DateTime DateAffectation { get; set; }
        public Nullable<bool> occupe { get; set; }
    
        public virtual service service { get; set; }
        public virtual utilisateur utilisateur { get; set; }
        public virtual vehicule vehicule { get; set; }
    }
}
