//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionConsommationVehiculeMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consommation
    {
        public int Id { get; set; }
        public int IdVehicule { get; set; }
        public int IdTypeConsommation { get; set; }
        public double quantite { get; set; }
        public int PrixUnitaire { get; set; }
        public double PrixTotal { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public System.DateTime DateConsommation { get; set; }
        public string NumeroDocument { get; set; }
        public Nullable<bool> Expirable { get; set; }
    
        public virtual typeconsommation typeconsommation { get; set; }
        public virtual vehicule vehicule { get; set; }
    }
}
