//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionConsommationVehiculeMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionConsommationVehiculeEntities12 : DbContext
    {
        public GestionConsommationVehiculeEntities12()
            : base("name=GestionConsommationVehiculeEntities12")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<affectation> affectations { get; set; }
        public DbSet<consommation> consommations { get; set; }
        public DbSet<profile> profiles { get; set; }
        public DbSet<service> services { get; set; }
        public DbSet<typeconsommation> typeconsommations { get; set; }
        public DbSet<utilisateur> utilisateurs { get; set; }
        public DbSet<vehicule> vehicules { get; set; }
    }
}
