//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionConsommationVehiculeMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        public service()
        {
            this.affectations = new HashSet<affectation>();
            this.utilisateurs = new HashSet<utilisateur>();
        }
    
        public int Id { get; set; }
        public string NomService { get; set; }
    
        public virtual ICollection<affectation> affectations { get; set; }
        public virtual ICollection<utilisateur> utilisateurs { get; set; }
    }
}
