//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionConsommationVehiculeMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class typeconsommation
    {
        public typeconsommation()
        {
            this.consommations = new HashSet<consommation>();
        }
    
        public int Id { get; set; }
        public string NomTypeConsommation { get; set; }
        public Nullable<bool> document { get; set; }
    
        public virtual ICollection<consommation> consommations { get; set; }
    }
}
