//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionConsommationVehiculeMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        public utilisateur()
        {
            this.affectations = new HashSet<affectation>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenon { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string telephone { get; set; }
        public int IdService { get; set; }
        public int IdProfile { get; set; }
    
        public virtual ICollection<affectation> affectations { get; set; }
        public virtual profile profile { get; set; }
        public virtual service service { get; set; }
    }
}
