//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionConsommationVehiculeMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicule
    {
        public vehicule()
        {
            this.affectations = new HashSet<affectation>();
            this.consommations = new HashSet<consommation>();
        }
    
        public int Id { get; set; }
        public string NumeroImatriculation { get; set; }
        public string modele { get; set; }
        public string marque { get; set; }
        public string NumeroCarteRose { get; set; }
        public string Numerochasse { get; set; }
        public string couleur { get; set; }
    
        public virtual ICollection<affectation> affectations { get; set; }
        public virtual ICollection<consommation> consommations { get; set; }
    }
}
